version: "3"

services:
  node:
    build:
      context: .
    restart: always
    ports:
    - "80:3000"
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
    - "127.0.0.1:27017:27017"
